# Generated by Django 5.2 on 2025-05-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
